### PR TITLE
Fixed synchronization of weathers and interiors

### LINKED ISSUE #43: Custom moons weather is not synced
For some reason, when you try to load a custom moon with LethalLevelLoader the weather of each individual moon becomes desyced between the clients and the server. **(It's not just a graphical bug!!!)**

The server sees this:
Server

Instead the Clients see this:
clients

### LINKED ISSUE #55: it spawned different dungeons on the same planet
**i have six friends playing together in the same room.But it spawned different dungeons on the same planet**
**This situation has been encountered many times, and this is the log of one of the interceptions.**

### Most of us have entered Minecraft Stronghold：
[Info   :LethalLevelLoader] Level: 61 March Contains DungeonFlow: Level1Flow3Exits In DungeonGenerator That Was Not Found In RoundManager, Adding!
[Info   :LethalLevelLoader] Re-Adjusting DungeonFlowTypes Array For Late Arriving Vanilla DungeonFlow
[Info   :LethalPosters] Patching GenerateNewLevelClientRpc in RoundManager
[Info   :LethalPosters] Patching the textures
[Info   :LethalPosters] Patching Posters (Instance) with G:\SteamLibrary\steamapps\common\Lethal Company\BepInEx\plugins\Nazarick-Nazarick_posters\LethalPosters\posters\1.png
[Info   :LethalPosters] Patching TipsPoster (Instance) with G:\SteamLibrary\steamapps\common\Lethal Company\BepInEx\plugins\Nazarick-Nazarick_posters\LethalPosters\tips\1.jpg
[Info   :LethalLevelLoader] Setting Random DungeonFlows!
[Warning:LethalLevelLoader] Disabling LethalLib Dungeon.RoundManager_GenerateNewFloor() Function To Prevent Conflicts
[Info   :ImoutoSama.ScarletMansion] Disabling SDM logic
[Error  : Unity Log] Only the owner can invoke a ServerRpc that requires ownership!
[Info   :LethalLevelLoader] Fire Exit Patch Report, Details Below;

EntranceTeleport's Found, March Contains 4 Entrances! ( 3 Fire Escapes) 
Main Entrance: EntranceTeleportA (Entrance ID: 0) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportB (Entrance ID: 1) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportC (Entrance ID: 2) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportD (Entrance ID: 3) (Dungeon ID: 5)
Found Fire Escape GlobalProp: (ID: 1231), Modifying Spawnrate Count From (1,1) To (3,3)

[Info   :LethalLevelLoader] Created New Day History Log! PlanetName: March , DungeonName: Minecraft Stronghold , Quota: 0 , Day: 2 , Weather: None
[Info   :LethalLevelLoader] PreProcessing
[Info   :LethalLevelLoader] MainPath

### One of us entered the ScarletMansion
[Info   :LethalLevelLoader] Level: 61 March Contains DungeonFlow: Level1Flow3Exits In DungeonGenerator That Was Not Found In RoundManager, Adding!
[Info   :LethalLevelLoader] Re-Adjusting DungeonFlowTypes Array For Late Arriving Vanilla DungeonFlow
[Info   :LethalPosters] Patching GenerateNewLevelClientRpc in RoundManager
[Info   :LethalPosters] Patching the textures
[Info   :LethalPosters] Patching Posters (Instance) with D:\SteamLibrary\steamapps\common\Lethal Company\BepInEx\plugins\Nazarick-Nazarick_posters\LethalPosters\posters\1.png
[Info   :LethalPosters] Patching TipsPoster (Instance) with D:\SteamLibrary\steamapps\common\Lethal Company\BepInEx\plugins\Nazarick-Nazarick_posters\LethalPosters\tips\1.jpg
[Info   :LethalLevelLoader] Setting Random DungeonFlows!
[Warning:LethalLevelLoader] Disabling LethalLib Dungeon.RoundManager_GenerateNewFloor() Function To Prevent Conflicts
[Info   :ImoutoSama.ScarletMansion] Disabling SDM logic
[Error  : Unity Log] Only the owner can invoke a ServerRpc that requires ownership!
[Info   :ImoutoSama.ScarletMansion] Loading Scarlet Mansion map so we are activating the alt. dungen scripts
[Info   :ImoutoSama.ScarletMansion] Set new dungeon bounds with, (0.00, 4.00, 58.67) and (240.00, 40.00, 133.33)
[Info   :ImoutoSama.ScarletMansion] Length of main path be: (12 - 15)
[Info   :ImoutoSama.ScarletMansion] Loaded custom enemies and items for Level4March
[Info   :ImoutoSama.ScarletMansion] Added Crawler:4 to bedroom event
[Info   :ImoutoSama.ScarletMansion] Added Jester:7 to bedroom event
[Info   :ImoutoSama.ScarletMansion] Added Nutcracker:8 to bedroom event
[Info   :ImoutoSama.ScarletMansion] Added SpringMan:18 to bedroom event
[Info   :ImoutoSama.ScarletMansion] Added Knight:19 to bedroom event
[Info   :LethalLevelLoader] Fire Exit Patch Report, Details Below;

EntranceTeleport's Found, March Contains 4 Entrances! ( 3 Fire Escapes) 
Main Entrance: EntranceTeleportA (Entrance ID: 0) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportB (Entrance ID: 1) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportC (Entrance ID: 2) (Dungeon ID: 5)
Alternate Entrance: EntranceTeleportD (Entrance ID: 3) (Dungeon ID: 5)
Found Fire Escape GlobalProp: (ID: 1231), Modifying Spawnrate Count From (1,1) To (3,3)

[Info   :LethalLevelLoader] Created New Day History Log! PlanetName: March , DungeonName: Scarlet Devil Mansion , Quota: 2 , Day: 9 , Weather: None
[Info   :LethalLevelLoader] PreProcessing
[Info   :LethalLevelLoader] MainPath

### LINKED ISSUE #57: [Bug] LLL seems to be causing weather desync
Hey there, I was following up on some bug reports in our mod pack and finally got back around to a weather desync.  As far as I can tell, it's caused by LLL (or a weird mod conflict with LLL).

Turned off essentially everything but LLL (and LLL-related mods), and weather will desync (even on vanilla moons).  Uninstalling LLL resyncs the weather and removes the issue.

image

test profile code: 018dfcc4-39ce-be84-e443-b9194deead10

### LINKED ISSUE #62: When will map desync be fixed??
This is an ongoing issue thats known online with a fanmade fix. Some players see a different map than others on cams and other players seemingly phase through walls. any updates?

### LINKED ISSUE #79: 1.2.2 Adding the interior and modifying the map at the same time will cause the map to be out of sync

### LINKED ISSUE #92: Desynchronization
Modded moons (exept of AudioKnight's Starlancer moons for some reason) have synchronization issue. Interiors (both modded and vanila) and weather are different for host and clients.

P.S. Autors of moons in question are sfDesat and Tolian

### PR DESCRIPTION
**Pull request by WhiteSpike**
- ServerRPCs can only be called by clients and ClientRPCs can only be called by server. The issue here was that the check made to call the ServerRPCs was only to see if it was a server, which doesn't make sense because the server can't make a ServerRPC call.

- Fixes #92 , fixes #79 , fixes #62 , fixes #57 , fixes #55 , fixes #43

### CODE REVIEW

**Comment by LinkTroisUn** [comment]
For the time those bugs are not fixed into the official version, would you know how I can compile those fixes myself ? I've tried multiple times to compile the mod from source, but I'm always blocked by private or internal attributes being accessed directly from the mod, which results in compilation error.

**Comment by RicardoCst** [comment]
Yes or could you upload your version to Thunderstore?

**Comment by WhiteSpike** [comment]
> For the time those bugs are not fixed into the official version, would you know how I can compile those fixes myself ? I've tried multiple times to compile the mod from source, but I'm always blocked by private or internal attributes being accessed directly from the mod, which results in compilation error.

Should just need to publicize ``Unity.Netcode.Runtime`` assembly.

**Comment by RicardoCst** [comment]
@WhiteSpike I will fork this repo and implement your fixes as a temporary solution if you approve.

**Comment by WhiteSpike** [comment]
> @WhiteSpike I will fork this repo and implement your fixes as a temporary solution if you approve.
> 
> Route to company and desyncs.

Fine by me. They worked between two local instances. I cannot guarantee that they are actually fixed as the weather/dungeon sync was a matter of data race.

Batby is thinking of an alternative solution to this as they do not wish to have all clients tell the server to execute code (which is what this fix does) but rather have server make a result and output it to all clients to use for weather/dungeon.

**Comment by RicardoCst** [comment]
Has to wait, there are a lot of libraries and referenced components locally so I need to remap those.

**Comment by RicardoCst** [comment]
https://thunderstore.io/c/lethal-company/p/ricardoandren/lethallevelloader_syncfix/

**Comment by LinkTroisUn** [comment]
> https://thunderstore.io/c/lethal-company/p/ricardoandren/lethallevelloader_syncfix/

I'm not sure that the fixes work.
When I try to land on a planet alone, the random seed screen waits for eternity, as if the dungeon never gets generated.

When someone tried to join me, they were stuck in a black screen. This one was caused by the SetPlanetsWeather_Postfix function (that had been modified with the fix)

After messing with the code myself and making that postfix function do nothing, the other player got kicked while I got the eternal random seed screen. (I was not sure what to change actually)

Note : for those tests, I had several modded planet mods that use LethalLevelLoader

**Comment by RicardoCst** [comment]
Hello,

I've been struggling with uploading to thunderstore and went through 4 versions in 4 hours, could be that I accidentally broke something, 1.2.10 should be uploaded correctly after an eternity, could you try as soon as the thunderstore has refreshed?

**Comment by RicardoCst** [comment]
Actually, I tried with my local version (without thunderstore) and the same issue happens, I think my build has failed and I will deprecate this (unfortunately)

**Comment by RicardoCst** [comment]
Then I wonder how @WhiteSpike has tested this. (No sarcasm intended)

> > https://thunderstore.io/c/lethal-company/p/ricardoandren/lethallevelloader_syncfix/
> 
> I'm not sure that the fixes work. When I try to land on a planet alone, the random seed screen waits for eternity, as if the dungeon never gets generated.
> 
> When someone tried to join me, they were stuck in a black screen. This one was caused by the SetPlanetsWeather_Postfix function (that had been modified with the fix)
> 
> After messing with the code myself and making that postfix function do nothing, the other player got kicked while I got the eternal random seed screen. (I was not sure what to change actually)
> 
> Note : for those tests, I had several modded planet mods that use LethalLevelLoader

Also thanks @LinkTroisUn for checking this aswell.

**Comment by WhiteSpike** [comment]
I didn't commit the changes I did on the csproj file. So if you haven't changed the paths according to your machine, it won't recognize core components to compile.

**Comment by RicardoCst** [comment]
> I didn't commit the changes I did on the csproj file. So if you haven't changed the paths according to your machine, it won't recognize core components to compile.

No we both correctly compiled it but it doesnt work

> I don't think your build has failed, because when I compiled the fix by myself, the same happened. It might be the way LethalLevelLoader is made that does not allow to change that portion of code (at least without big changes).

**Comment by WhiteSpike** [comment]
> > I didn't commit the changes I did on the csproj file. So if you haven't changed the paths according to your machine, it won't recognize core components to compile.
> 
> No we both correctly compiled it but it doesnt work
> 
> > I don't think your build has failed, because when I compiled the fix by myself, the same happened. It might be the way LethalLevelLoader is made that does not allow to change that portion of code (at least without big changes).

I made sure I had the necessary dependencies and that MY .dll was the one used to be LethalLevelLoader, NOT the one in the Thunderstore.

**Comment by RicardoCst** [comment]
I ran it locally without thunderstore, I cant tell for the other person that tried it aswell, but honestly this is way too complicated for me.

This is what I had edited in my own csproj to match my paths:

https://github.com/IAmBatby/LethalLevelLoader/commit/dc192d97e1f82aac497a8779ae4adaf882609535

**Comment by WhiteSpike** [comment]
Don't really see a reason for it to not work.
Post the logs here and I will take a look.

**Comment by LinkTroisUn** [comment]
> I ran it locally without thunderstore, I cant tell for the other person that tried it aswell, but honestly this is way too complicated for me.

I overwrited the dll of LethalLevelLoader in the Bepinex/plugins/<insert lethal level loader path>/ folder with my self compiled one

**Comment by RicardoCst** [comment]
The only logs I get with Log Level: Debug, Unity logs and LethaLevelLoader logs are:


>> [Info   : Unity Log] Now listening to dungeon generator status. <<
[Info   : Unity Log] clip index: 2; current planet: 41 Experimentation
[Info   : Unity Log] Current ship ambience clips length: 12
[Info   : Unity Log] clip index: 7; current planet: 41 Experimentation
[Info   : Unity Log] Current ship ambience clips length: 12

After this no more logs, everything just stops.

**Comment by RicardoCst** [comment]
More extensive log and screenshot:
[LogOutput.log](https://github.com/IAmBatby/LethalLevelLoader/files/15313582/LogOutput.log)



afbeelding

**Comment by WhiteSpike** [comment]
> More extensive log and screenshot: [LogOutput.log](https://github.com/IAmBatby/LethalLevelLoader/files/15313582/LogOutput.log)
> 
> afbeelding

I forgot the case of just being the host (Because if there are no clients other than host, it won't sync thus this is not a good solution). I will think of a better way for this later.

**Pull request closed without merging**
