### PR TITLE
Pure dotnet build

### PR DESCRIPTION
**Pull request by wherget**
This Pull Request replaces all local dependencies with ones from nuget, and cleans up some minor things to make LLL build using a simple `dotnet build`. No need to even have LC installed. The goal being, to be able to eventually run an automated build in a gitlab workflow.

Points possibly worthy of further discussion:
- I dropped the `UnityEditor.dll` dependency. This is no problem for the mod build, as only `ExtendedScriptableObjectDrawer` would use it. IAmBatby told me on discord the general workflow (as of this PR) is to dump this code into a Custom Content project, so it should build there without issue? I haven't tested this yet.
- The `GameLibs` dependency currently needs `Publicize` only due to `GenerateScenesInBuild_Hook`, which accesses the `internal Hash()` function. This isn't a problem per se, but I feel it might help avoid bugs if at LLL development time we could see which LC fields are private. Publicise hides this from our view.
- The `NetcodePatcher` docs say the SDK usage (instead of using the cli tool) might break the build in Visual Studio. I haven't verified this. It works fine in VS Code obviously.

I have verified this builds and doesn't change any functionality when used in LC.

### CODE REVIEW

**Comment by RicardoCst** [comment]
Used in my branch works perfect, thanks a lot.

**Comment by RicardoCst** [comment]
Used in #101 but build didnt come out netcode patched:

`<Exec Command="netcode-patch &quot;$(TargetPath)&quot; @(ReferencePathWithRefAssemblies->'&quot;%(Identity)&quot;', ' ')" />`

**Comment by wherget** [comment]
So it turns out I may have skimmed the NetcodePatcher docs a little too fast. 😅 With the current changes it tries to NetcodePatch at least, but on my end I'm still getting errors while patching, which may be contingent upon EvaisaDev/UnityNetcodePatcher#40 and require a new release from them.

So hold off on merging this for now, I may need to bump a version still before everything works.

**Comment by wherget** [comment]
In the light of v55 approaching I wanted to get this moved along. This is now the state where it works using `dotnet build` but not in Visual Studio. I have a solution which makes it work for both, but that necessitates another change in NetcodePatcher unfortunately. I thought I would have gotten around to it by now, sorry. If you can live with `dotnet build`ing for now, feel free to merge.

**Pull request merged**
