### PR TITLE
Attempt number two of fixing weather/dungeon synchronization

### PR DESCRIPTION
**Pull request by WhiteSpike**
- Host is the only one that executes ``SetPlanetWeathers`` during ``TimeOfDay.OnDayPassed``. Sends the output of weathers to all clients.
- On ``StartOfRound.OnPlayerConnectedClientRpc``, the client requests to the server/host client for the current weathers to be sent to them on join to be synchronized with the lobby.
- Removed ``SetPlanetsWeather`` postfix patch as they weren't being used.
- Split logic between functions.

Tests:
- Two local instances (aka latency is pratically non-existent thus it's not reliable testing for this case)
- Just the host (didn't seem to freeze compared to last time)

### CODE REVIEW

**Comment by RicardoCst** [comment]
Would you like to test this with latency soon? If it works I can try another build.

**Comment by RicardoCst** [comment]
Stuck in:
afbeelding

**Comment by WhiteSpike** [comment]
That's because AssetBundleLoader is destroyed before it finishes loading the asset bundles. (Which is not fixed in this PR)

**Comment by RicardoCst** [comment]
I removed             DontDestroyOnLoad(test);
And uncommented              //test.hideFlags = HideFlags.HideAndDontSave;

Now it works, tested and dont seem to break game in a major way.

**Comment by RicardoCst** [comment]
I noticed one thing:

It seems that moons at the start of a new save file always get the following weather:

afbeelding

**Comment by RicardoCst** [comment]
afbeelding

afbeelding

Latency is a problem.

**Comment by RicardoCst** [comment]
[Marius.txt](https://github.com/IAmBatby/LethalLevelLoader/files/15369114/Marius.txt)
[Ricardo.txt](https://github.com/IAmBatby/LethalLevelLoader/files/15369115/Ricardo.txt)

Here you go, the only thing I notice is:

afbeelding

**Comment by RicardoCst** [comment]
And heres the more extensive debug from my side.
[RicardoDebug.txt](https://github.com/IAmBatby/LethalLevelLoader/files/15369162/RicardoDebug.txt)

**Comment by WhiteSpike** [comment]
> [Marius.txt](https://github.com/IAmBatby/LethalLevelLoader/files/15369114/Marius.txt) [Ricardo.txt](https://github.com/IAmBatby/LethalLevelLoader/files/15369115/Ricardo.txt)
> 
> Here you go, the only thing I notice is:
> 
> afbeelding

For some reason, only the host is executing the clientRPC when it's supposed for everyone to execute it.
The build you used didn't seem to be netcode patched as I don't find any of the generated functions for each RPC implementation.

**Comment by RicardoCst** [comment]
Sorry thats my fault, I used #106 

Theres a commit that changes

<Exec Command="netcode-patch &quot;$(TargetPath)&quot; @(ReferencePathWithRefAssemblies->'&quot;%(Identity)&quot;', ' ')" />

into:

<NetcodePatch Include="$(TargetPath)" />

**Comment by RicardoCst** [comment]
Tried netcode-patching, failed aswell, I will stop working on this now due to a lack of time. This is way more complicated than just trying to patch a small snippet of code. What I notice is that the moment it hangs is the same as with your previous pull request and thats about it.


https://github.com/RicardoCst/LethalLevelLoader-SyncFix

**Comment by LinkTroisUn** [comment]
Tested WhiteSpike's fix with 2 local client separeted over the internet, and with mods that require LLL,
Seems to work (for dungeon and weather) as long as the game is not restarted. When I restarted the game (I mean close Lethal Company then launch Lethal company again), the non host client could either not enter the main entrance, or fall into the void.
This seems to be solved by rebooting both computers.
Several weird fatal looking exceptions kept being throwned in both working and not working cases

**Comment by RicardoCst** [comment]
> Seems to work (for dungeon and weather) as long as the game is not restarted. When I restarted the game (I mean close Lethal Company then launch Lethal company again), the non host client could either not enter the main entrance, or fall into the void.

Anything you changed in WhiteSpikes code?

> I removed DontDestroyOnLoad(test); And uncommented //test.hideFlags = HideFlags.HideAndDontSave;
> 
> Now it works, tested and dont seem to break game in a major way.

I had this issue without changing anything and just building the fork.

**Comment by LinkTroisUn** [comment]
> Anything you changed in WhiteSpikes code?

Normally, I have not changed anything
 
> I had this issue without changing anything and just building the fork.

These lines were already like this when I cloned his fork

**Comment by LinkTroisUn** [comment]
However, I built the fork using everything as nuget package, except MHOOK. I also publicized... I think Unity.netcode.runtime from the nuget package

**Comment by RicardoCst** [comment]
I did that too originally using #106

**Comment by LinkTroisUn** [comment]
I did not follow #106 to do it.

Now, I've also tested the 1.2.4 version of LLL. All test cases I have done previously for dungeon and weather sync seemed to work with that version, but the ship was less stable, being unable to take off after certain mods events

**Pull request closed without merging**
